apiVersion: v1
kind: Service
metadata:
  name: books-api-service
  namespace: books-api
spec:
  type: ClusterIP
  selector:
    app: books-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081